esphome:
  min_version: 2024.11.0

logger:
  level: INFO

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

mqtt:
  broker: 10.168.1.4
  port: 1883
  username: !secret mqtt_user
  password: !secret mqtt_password

web_server:
  port: 80

ota:
  - platform: esphome

api:

binary_sensor:
  - platform: status
    name: Status

sensor:

  - platform: mqtt_subscribe
    name: "Temperature"
    id: temp_sensor
    state_topic: "main/temp1"
    unit_of_measurement: "째C"
    on_value:
      then:
        - lambda: |-
            char buf[16];
            sprintf(buf, "%.1f 째C", x);
            id(temp_label).set_text(buf);
            
  - id: wifi_signal_db
    name: WiFi Signal
    platform: wifi_signal
    update_interval: 60s
    entity_category: diagnostic

  - id: wifi_signal_strength
    name: WiFi Strength
    platform: copy
    source_id: wifi_signal_db
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: diagnostic
    
  - platform: mqtt_subscribe
    name: "Temperature"
    id: temp_sensor
    state_topic: "main/temp1"
    unit_of_measurement: "째C"
    on_value:
      then:
        - lambda: |-
            char buf[16];
            sprintf(buf, "Temp: %.1f 째C", x);
            lv_label_set_text(id(temperature_label), buf);

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address
      entity_category: diagnostic
    ssid:
      name: Connected SSID
      entity_category: diagnostic
    mac_address:
      name: Mac Address
      entity_category: diagnostic
